package org.etk.core.rest.impl;

import java.util.HashMap;

/**
 * Keeps objects from environment (e. g. servlet container) which can be passed
 * in resource. Parameter must be annotated by {@link javax.ws.rs.core.Context}.
 * 
 */
public class EnvironmentContext extends HashMap<Class<?>, Object> {

  /**
   * Generated by Eclipse.
   */
  private static final long                      serialVersionUID = 5409617947238152318L;

  /**
   * {@link ThreadLocal} EnvironmentContext.
   */
  private static ThreadLocal<EnvironmentContext> current          = new ThreadLocal<EnvironmentContext>();

  /**
   * @return preset {@link ThreadLocal} EnvironmentContext
   * @see ThreadLocal
   */
  public static EnvironmentContext getCurrent() {
    return current.get();
  }

  /**
   * @param env set {@link ThreadLocal} EnvironmentContext
   * @see ThreadLocal
   */
  public static void setCurrent(EnvironmentContext env) {
    current.set(env);
  }

}
