package org.etk.core.rest.impl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.etk.core.rest.ExtMultivaluedMap;


public class MultivaluedMapImpl extends HashMap<String, List<String>> implements ExtMultivaluedMap<String, String> {

  /**
   * Generated by Eclipse.
   */
  private static final long serialVersionUID = -6066678602537059655L;

  /**
   * {@inheritDoc}
   */
  public void add(String key, String value) {
    if (value == null)
      return;

    List<String> list = getList(key);
    list.add(value);
  }

  /**
   * {@inheritDoc}
   */
  public String getFirst(String key) {
    List<String> list = get(key);
    return list != null && list.size() > 0 ? list.get(0) : null;
  }

  /**
   * {@inheritDoc}
   */
  public void putSingle(String key, String value) {
    if (value == null)
      return;

    List<String> list = getList(key);
    list.clear();
    list.add(value);
  }

  /**
   * {@inheritDoc}
   */
  public List<String> getList(String key) {
    List<String> list = get(key);
    if (list == null) {
      list = new ArrayList<String>();
      put(key, list);
    }
    return list;
  }

}
